$freq = tail_CON.freq; 
$delay = tail_CON.frameDelay;
$fps = tail_CON.fps;

$xAmp = tail_CON.xAmplitude;
$yAmp = tail_CON.yAmplitude;
$zAmp = tail_CON.zAmplitude;
$xN = tail_CON.xNoise;
$yN = tail_CON.yNoise;
$zN = tail_CON.zNoise;
$xOfs = tail_CON.xOffset;
$yOfs = tail_CON.yOffset;
$zOfs = tail_CON.zOffset;

proc float calc(int $i, float $localOffset) {
    return ($freq * (time * $fps - tail_CON.globalOffset) - $i * $delay - $localOffset)  / $fps;
}

T_Noise1.translateX = $xAmp * sind(360 * calc(1, $xOfs)) + $xN * noise (calc(1, $xOfs));
T_Noise2.translateX = $xAmp * sind(360 * calc(2, $xOfs)) + $xN * noise (calc(2, $xOfs));
T_Noise3.translateX = $xAmp * sind(360 * calc(3, $xOfs)) + $xN * noise (calc(3, $xOfs));
T_Noise4.translateX = $xAmp * sind(360 * calc(4, $xOfs)) + $xN * noise (calc(4, $xOfs));
T_Noise5.translateX = $xAmp * sind(360 * calc(5, $xOfs)) + $xN * noise (calc(5, $xOfs));
T_Noise6.translateX = $xAmp * sind(360 * calc(6, $xOfs)) + $xN * noise (calc(6, $xOfs));
T_Noise7.translateX = $xAmp * sind(360 * calc(7, $xOfs)) + $xN * noise (calc(7, $xOfs));

T_Noise1.translateY = $yAmp * sind(360 * calc(1, $yOfs)) + $yN * noise (calc(1, $yOfs));
T_Noise2.translateY = $yAmp * sind(360 * calc(2, $yOfs)) + $yN * noise (calc(2, $yOfs));
T_Noise3.translateY = $yAmp * sind(360 * calc(3, $yOfs)) + $yN * noise (calc(3, $yOfs));
T_Noise4.translateY = $yAmp * sind(360 * calc(4, $yOfs)) + $yN * noise (calc(4, $yOfs));
T_Noise5.translateY = $yAmp * sind(360 * calc(5, $yOfs)) + $yN * noise (calc(5, $yOfs));
T_Noise6.translateY = $yAmp * sind(360 * calc(6, $yOfs)) + $yN * noise (calc(6, $yOfs));
T_Noise7.translateY = $yAmp * sind(360 * calc(7, $yOfs)) + $yN * noise (calc(7, $yOfs));

T_Noise1.translateZ = $zAmp * sind(360 * calc(1, $zOfs)) + $zN * noise (calc(1, $zOfs));
T_Noise2.translateZ = $zAmp * sind(360 * calc(2, $zOfs)) + $zN * noise (calc(2, $zOfs));
T_Noise3.translateZ = $zAmp * sind(360 * calc(3, $zOfs)) + $zN * noise (calc(3, $zOfs));
T_Noise4.translateZ = $zAmp * sind(360 * calc(4, $zOfs)) + $zN * noise (calc(4, $zOfs));
T_Noise5.translateZ = $zAmp * sind(360 * calc(5, $zOfs)) + $zN * noise (calc(5, $zOfs));
T_Noise6.translateZ = $zAmp * sind(360 * calc(6, $zOfs)) + $zN * noise (calc(6, $zOfs));
T_Noise7.translateZ = $zAmp * sind(360 * calc(7, $zOfs)) + $zN * noise (calc(7, $zOfs));